### ISSUE TITLE
pop up message shown while dragging two stand alone cartridges is persisted.

### ISSUE THREAD

**Issue by sandeeppanem** [ssbanerje/openshift-workflows#16] opened 2012-11-08 20:47 UTC
when added 2 standalone cartridges it gives pop Standalone cartridge already exists. But when again data base cartridge is dragged onto node.. that message should not appear.

**Comment by ssbanerje** [comment] 2012-11-09 06:55
dupe of #8 ---> closing!

**Closed as completed by ssbanerje** 2012-11-09 06:55 UTC
Labels: bug
